openapi: 3.0.0
info:
  title: Google Tasks API Proxy
  version: 1.0.0
  description: Proxy API for Google Tasks
paths:
  /api/tasks/{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
        - name: proxy
          in: path
          required: true
          schema:
            type: string
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:${AWS_REGION}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS_REGION}:${AWS_ACCOUNT_ID}:function:google-tasks-proxy/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
        timeoutInMillis: 29000
x-amazon-apigateway-binary-media-types:
  - "*/*"
x-amazon-apigateway-cors:
  allowOrigins:
    - "*"
  allowMethods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowHeaders:
    - Content-Type
    - Authorization
    - X-Requested-With
  maxAge: 600
